version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/examples/coffee-warehouse-nextjs"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/ecommerce-jewellery-store"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-e-commerce-astro-app"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-build-a-sales-dashboard"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-file-manager"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-finance-portfolio"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-homepage-demo"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-nextjs"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-sales-dashboard"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-ssr"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/kendo-react-stackblitz-app"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/react-admin-dashboard"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/examples/react-coffee-warehouse"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"
  
  - package-ecosystem: "npm"
    directory: "/examples/react-grid-live-data"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    groups:
      kendo-dependencies:
        patterns:
          - '@progress/kendo-*'
    allow:
      - dependency-name: '@progress/kendo-*'
    commit-message:
      prefix: "chore:"
    reviewers:
      - "telerik/kendo-react-devs"
      - "telerik/kendo-react-support"
    labels:
      - "Dependencies"